name: good_old_solitaire
description: "Play good old Solitaire on your phone."
publish_to: 'none'
version: 0.1.0

#
# DEPLOYING APP
# 1. `pubspec.yaml` -> Bump version number
# 2. `release_notes.txt` -> Update changelog for all languages
# 3. `default.txt` -> Update changelog for all languages
#

#
# Android
# `cd android/ && fastlane play_store_release`
#
# GitHub Releases
# `cd android/ && fastlane github_release`
#
# iOS
# `cd ios/ && fastlane app_store_release`
#

environment:
  sdk: 3.10.8

dependencies:
  flutter:
    sdk: flutter

  audioplayers: 6.5.1
  flutter_animate: 4.5.2
  get_it: 9.2.0
  hive_ce: 2.19.1
  hive_ce_flutter: 2.3.4
  just_audio: 0.10.5
  logger: 2.6.2
  package_info_plus: 9.0.0
  phosphor_flutter: 2.1.0
  watch_it: 2.4.1

dev_dependencies:
  build_runner: 2.10.5
  flutter_launcher_icons: 0.14.4
  flutter_native_splash: 2.4.7
  hive_ce_generator: 1.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/

# Run code generation - `flutter pub run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'flutter pub run flutter_launcher_icons:main'
flutter_launcher_icons:
  image_path_android: 'assets/icon.png'
  image_path_ios: 'assets/icon.png'
  android: true
  ios: true
  adaptive_icon_background: 'assets/background.png'
  adaptive_icon_foreground: 'assets/splash_icon.png'
  adaptive_icon_foreground_inset: 16
  adaptive_icon_monochrome: 'assets/monochrome.png'
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: '#EDEDF4'
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#EDEDF4'
    theme_color: '#EDEDF4'
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  background_image: 'assets/splash.png'
  background_image_dark: 'assets/splash_dark.png'
  android_12:
    image: 'assets/splash_icon.png'
    image_dark: 'assets/monochrome.png'
    color: '#EDEDF4'
    color_dark: '#1D2024'
